# Generated by Django 2.1.7 on 2019-03-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_no', models.IntegerField(unique=True)),
                ('dep_name', models.CharField(max_length=250)),
                ('schoolarshipORgovernment', models.CharField(max_length=250)),
                ('pointType', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('dep_cap', models.IntegerField()),
                ('min_rank', models.IntegerField()),
                ('min_point', models.DecimalField(decimal_places=5, max_digits=8)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='home.University'),
        ),
        migrations.AlterUniqueTogether(
            name='year',
            unique_together={('department', 'year')},
        ),
    ]
