# Generated by Django 2.1.7 on 2019-03-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190327_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='min_point',
            field=models.FloatField(),
        ),
    ]
